# Generated by Django 5.1 on 2024-08-27 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
